// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_border
#define IOD_SYMBOL_border
    iod_define_symbol(border)
#endif

#ifndef IOD_SYMBOL_detector_period
#define IOD_SYMBOL_detector_period
    iod_define_symbol(detector_period)
#endif

#ifndef IOD_SYMBOL_detector_th
#define IOD_SYMBOL_detector_th
    iod_define_symbol(detector_th)
#endif

#ifndef IOD_SYMBOL_keypoint_spacing
#define IOD_SYMBOL_keypoint_spacing
    iod_define_symbol(keypoint_spacing)
#endif

#ifndef IOD_SYMBOL_local_maxima
#define IOD_SYMBOL_local_maxima
    iod_define_symbol(local_maxima)
#endif

#ifndef IOD_SYMBOL_no_threads
#define IOD_SYMBOL_no_threads
    iod_define_symbol(no_threads)
#endif

#ifndef IOD_SYMBOL_record_video
#define IOD_SYMBOL_record_video
    iod_define_symbol(record_video)
#endif

#ifndef IOD_SYMBOL_video
#define IOD_SYMBOL_video
    iod_define_symbol(video)
#endif

#ifndef IOD_SYMBOL_type_of_distance
#define IOD_SYMBOL_type_of_distance
    iod_define_symbol(type_of_distance)
#endif

#ifndef IOD_SYMBOL_type_of_kalman_filter
#define IOD_SYMBOL_type_of_kalman_filter
    iod_define_symbol(type_of_kalman_filter)
#endif

#ifndef IOD_SYMBOL_life_time_threshold
#define IOD_SYMBOL_life_time_threshold
    iod_define_symbol(life_time_threshold)
#endif

#ifndef IOD_SYMBOL_distance_threshold
#define IOD_SYMBOL_distance_threshold
    iod_define_symbol(distance_threshold)
#endif

#ifndef IOD_SYMBOL_missed_frame_threshold
#define IOD_SYMBOL_missed_frame_threshold
    iod_define_symbol(missed_frame_threshold)
#endif

#ifndef IOD_SYMBOL_magnitude_acceleration_noise
#define IOD_SYMBOL_magnitude_acceleration_noise
    iod_define_symbol(magnitude_acceleration_noise)
#endif

#ifndef IOD_SYMBOL_life_time_supression_threshold
#define IOD_SYMBOL_life_time_supression_threshold
    iod_define_symbol(life_time_supression_threshold)
#endif

#ifndef IOD_SYMBOL_age_supression_threshold
#define IOD_SYMBOL_age_supression_threshold
    iod_define_symbol(age_supression_threshold)
#endif



